feat: docker hub

diff --git a/.github/workflows/deploy-server-with-compose.yml b/.github/workflows/deploy-server-with-compose.yml
--- a/.github/workflows/deploy-server-with-compose.yml
+++ b/.github/workflows/deploy-server-with-compose.yml
@@ -23,3 +23,16 @@ jobs:
       - name: push to dockerhub
         run: docker push ynlee557/ordersystem:latest
 
+      - name: ec2 ssh login and docker compose update
+        uses: appleboy/ssh-action@master
+        with:
+          host: ec2-3-34-43-81.ap-northeast-2.compute.amazonaws.com
+          username: ubuntu
+          key: ${{secrets.EC2_PEMKEY}}
+          script: |
+            if ! type docker > /dev/null; then
+              sudo snap install docker || echo "[failed] Docker install"
+            fi
+            sudo docker login --username ${{secrets.DOCKER_USERENAME}} --password ${{secrets.DOCKER_PASSWORD}}
+            
+            sudo docker-compose pull && sudo docker-compose up -d
